Fixes #29156: webapp non-root: fix postinst in rudder-plugins

diff --git a/change-validation/packaging/postinst b/change-validation/packaging/postinst
--- a/change-validation/packaging/postinst
+++ b/change-validation/packaging/postinst
@@ -1,41 +1,43 @@
 #!/bin/bash
 set -e
-SQL_CREDENTIALS=$(grep -c -E "^rudder.jdbc.(username|password)[ \t]*=" /opt/rudder/etc/rudder-web.properties || true)
 
-if [ -f /opt/rudder/etc/rudder-web.properties -a ${SQL_CREDENTIALS} -eq 2 ]; then
-  # Get the database access credentials from the rudder-web.properties file
-  SQL_USER="$(grep -E '^rudder.jdbc.username[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d "=" -f 2-)"
-  SQL_PASSWORD="$(grep -E '^rudder.jdbc.password[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d "=" -f 2-)"
-  SQL_SERVER="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\1%')"
-  SQL_PORT="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\2%')"
-  SQL_DATABASE="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://.*:.*/\(.*\)$%\1%')"
+su - rudder-webapp <<'EOF'
+  SQL_CREDENTIALS=$(grep -c -E "^rudder.jdbc.(username|password)[ \t]*=" /opt/rudder/etc/rudder-web.properties || true)
 
-  export PGPASSWORD="${SQL_PASSWORD}"
-else
-  # No database access credentials in rudder-web.properties... Try anyway using "guessed" values.
-  echo "WARNING: Database access credentials are missing in /opt/rudder/etc/rudder-web.properties, trying to guess adequate values."
+  if [ -f /opt/rudder/etc/rudder-web.properties -a ${SQL_CREDENTIALS} -eq 2 ]; then
+    # Get the database access credentials from the rudder-web.properties file
+    SQL_USER="$(grep -E '^rudder.jdbc.username[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d "=" -f 2-)"
+    SQL_PASSWORD="$(grep -E '^rudder.jdbc.password[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d "=" -f 2-)"
+    SQL_SERVER="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\1%')"
+    SQL_PORT="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\2%')"
+    SQL_DATABASE="$(grep -E '^rudder.jdbc.url[ \t]*=' /opt/rudder/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://.*:.*/\(.*\)$%\1%')"
 
-  SQL_USER="rudder"
-  SQL_PASSWORD="Normation"
-  SQL_SERVER="localhost"
-  SQL_PORT="5432"
+    export PGPASSWORD="${SQL_PASSWORD}"
+  else
+    # No database access credentials in rudder-web.properties... Try anyway using "guessed" values.
+    echo "WARNING: Database access credentials are missing in /opt/rudder/etc/rudder-web.properties, trying to guess adequate values."
 
-  # We rely on .pgpass instead
-  unset PGPASSWORD
-fi
+    SQL_USER="rudder"
+    SQL_PASSWORD="Normation"
+    SQL_SERVER="localhost"
+    SQL_PORT="5432"
 
-PSQL="psql -t -q -h ${SQL_SERVER} -p ${SQL_PORT} -U ${SQL_USER}"
+    # We rely on .pgpass instead
+    unset PGPASSWORD
+  fi
 
-# Run SQL script to update schema. This script is reentrant, so you can run it as much as you need
-echo -n "Ensuring that Rudder validated users schema is up to date"
-${PSQL} -d ${SQL_DATABASE} -f /opt/rudder/share/plugins/change-validation/change-validation-schema.sql
-echo " Done"
+  PSQL="psql -t -q -h ${SQL_SERVER} -p ${SQL_PORT} -U ${SQL_USER}"
 
-# Notification's configuration file
-cp /opt/rudder/share/plugins/change-validation/change-validation.conf /opt/rudder/etc/plugins/
-mkdir -p /var/rudder/plugins/change-validation
-cp /opt/rudder/share/plugins/change-validation/validation-mail.template /var/rudder/plugins/change-validation
-cp /opt/rudder/share/plugins/change-validation/deployment-mail.template /var/rudder/plugins/change-validation
-cp /opt/rudder/share/plugins/change-validation/cancelled-mail.template /var/rudder/plugins/change-validation
-cp /opt/rudder/share/plugins/change-validation/deployed-mail.template /var/rudder/plugins/change-validation
+  # Run SQL script to update schema. This script is reentrant, so you can run it as much as you need
+  echo -n "Ensuring that Rudder validated users schema is up to date"
+  ${PSQL} -d ${SQL_DATABASE} -f /opt/rudder/share/plugins/change-validation/change-validation-schema.sql
+  echo " Done"
 
+  # Notification's configuration file
+  cp /opt/rudder/share/plugins/change-validation/change-validation.conf /opt/rudder/etc/plugins/
+  mkdir -p /var/rudder/plugins/change-validation
+  cp /opt/rudder/share/plugins/change-validation/validation-mail.template /var/rudder/plugins/change-validation
+  cp /opt/rudder/share/plugins/change-validation/deployment-mail.template /var/rudder/plugins/change-validation
+  cp /opt/rudder/share/plugins/change-validation/cancelled-mail.template /var/rudder/plugins/change-validation
+  cp /opt/rudder/share/plugins/change-validation/deployed-mail.template /var/rudder/plugins/change-validation
+EOF
diff --git a/datasources/packaging/postinst b/datasources/packaging/postinst
--- a/datasources/packaging/postinst
+++ b/datasources/packaging/postinst
@@ -1,35 +1,38 @@
 #!/bin/bash
 set -e
-# Postinstall for Rudder datasource plugin
-RUDDER_OPT="/opt/rudder"
 
-SQL_CREDENTIALS=$(grep -c -E "^rudder.jdbc.(username|password)[ \t]*=" /opt/rudder/etc/rudder-web.properties || true)
+su - rudder-webapp <<'EOF'
+  # Postinstall for Rudder datasource plugin
+  RUDDER_OPT="/opt/rudder"
 
-if [ -f /opt/rudder/etc/rudder-web.properties -a ${SQL_CREDENTIALS} -eq 2 ]; then
-  # Get the database access credentials from the rudder-web.properties file
-  SQL_USER="$(grep -E '^rudder.jdbc.username[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
-  SQL_PASSWORD="$(grep -E '^rudder.jdbc.password[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
-  SQL_SERVER="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\1%')"
-  SQL_PORT="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\2%')"
-  SQL_DATABASE="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://.*:.*/\(.*\)$%\1%')"
+  SQL_CREDENTIALS=$(grep -c -E "^rudder.jdbc.(username|password)[ \t]*=" /opt/rudder/etc/rudder-web.properties || true)
 
-  export PGPASSWORD="${SQL_PASSWORD}"
-else
-  # No database access credentials in rudder-web.properties... Try anyway using "guessed" values.
-  echo "WARNING: Database access credentials are missing in /opt/rudder/etc/rudder-web.properties, trying to guess adequate values."
+  if [ -f /opt/rudder/etc/rudder-web.properties -a ${SQL_CREDENTIALS} -eq 2 ]; then
+    # Get the database access credentials from the rudder-web.properties file
+    SQL_USER="$(grep -E '^rudder.jdbc.username[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
+    SQL_PASSWORD="$(grep -E '^rudder.jdbc.password[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
+    SQL_SERVER="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\1%')"
+    SQL_PORT="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://\(.*\):\(.*\)/.*$%\2%')"
+    SQL_DATABASE="$(grep -E '^rudder.jdbc.url[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2- | sed 's%^.*://.*:.*/\(.*\)$%\1%')"
 
-  SQL_USER="rudder"
-  SQL_PASSWORD="Normation"
-  SQL_SERVER="localhost"
-  SQL_PORT="5432"
+    export PGPASSWORD="${SQL_PASSWORD}"
+  else
+    # No database access credentials in rudder-web.properties... Try anyway using "guessed" values.
+    echo "WARNING: Database access credentials are missing in /opt/rudder/etc/rudder-web.properties, trying to guess adequate values."
 
-  # We rely on .pgpass instead
-  unset PGPASSWORD
-fi
+    SQL_USER="rudder"
+    SQL_PASSWORD="Normation"
+    SQL_SERVER="localhost"
+    SQL_PORT="5432"
 
-PSQL="psql -t -q -h ${SQL_SERVER} -p ${SQL_PORT} -U ${SQL_USER}"
+    # We rely on .pgpass instead
+    unset PGPASSWORD
+  fi
 
-# Run SQL script to update schema. This script is reentrant, so you can run it as much as you need
-echo -n "Ensuring that database schema is up to date"
-${PSQL} -d ${SQL_DATABASE} -f /opt/rudder/share/plugins/datasources/datasources-schema.sql
-echo " Done"
+  PSQL="psql -t -q -h ${SQL_SERVER} -p ${SQL_PORT} -U ${SQL_USER}"
+
+  # Run SQL script to update schema. This script is reentrant, so you can run it as much as you need
+  echo -n "Ensuring that database schema is up to date"
+  ${PSQL} -d ${SQL_DATABASE} -f /opt/rudder/share/plugins/datasources/datasources-schema.sql
+  echo " Done"
+EOF
